### ISSUE TITLE
Test support for Python 3.11

### ISSUE THREAD

**Issue by john-science** [terrapower/armi#957]
This could be as easy as adding it to the GitHub workflow.

But some local testing wouldn't hurt.

**Comment by john-science** [comment]
Currently, the blocker on this is `mpi4py` isn't compiling for Linux  on Python 3.11.

Please see [this](https://github.com/mpi4py/mpi4py/issues/273) bug report for mpi4py.

**Comment by dalcinl** [comment]
@john-science [mpi4py 3.4.1](https://github.com/mpi4py/mpi4py/releases/tag/3.1.4) should resolve your issue.

**Comment by john-science** [comment]
Thanks, @dalcinl !  That fixed the `mpi4py` issue!

**Comment by john-science** [comment]
The current stopping block is [h5py](https://pypi.org/project/h5py/#files) does not have an official Python 3.11 release yet.

They have an [issue](https://github.com/h5py/h5py/issues/2146) open for this though.

**Comment by john-science** [comment]
H5PY is still the limiting factor.  I can't seem to successfully [install it in Python 3.11](https://github.com/john-science/armi/actions/runs/3681061169/jobs/6227339055):

```
      Loading library to get build settings and version: libhdf5.so
      error: Unable to load dependency HDF5, make sure HDF5 is installed properly
      error: libhdf5.so: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
```

...

```
Building wheels for collected packages: h5py
  Building wheel for h5py (pyproject.toml): started
  Building wheel for h5py (pyproject.toml): finished with status 'error'
Failed to build h5py
mpitest: exit 1 (10.07 seconds) /home/runner/work/armi/armi> python -I -m pip install configparser coverage future 'h5py>=3.0' htmltree matplotlib numpy ordered-set pillow pluggy pyDOE pyevtk scipy tabulate voluptuous xlrd yamlize pid=3408
.pkg: _exit> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  test: FAIL code 1 (50.61 seconds)
```

So, we can't just install the version-dependent tarball from the h5py team. We need to wait for a wheel from them. After much work, it appears that all our non-h5py unit tests pass in Python 3.11.  I think this is out last hold-out.

**Comment by john-science** [comment]
> Can you try `sudo apt install libhdf5-dev` before running tox?

That worked!

It doesn't help our Windows users. But it gives me a stop-gap to test in 3.11 in Linux (which is my preference anyway).

Thanks, man!

**Comment by john-science** [comment]
@scThe current road block for getting ARMI working in Python 3.11 appears to be the [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) library. Our unit tests throw:

```python
armi/cli/reportsEntryPoint.py:21: in <module>
    from armi.reactor import blueprints
armi/reactor/blueprints/__init__.py:77: in <module>
    from ruamel.yaml import CLoader, RoundTripLoader
E   ImportError: cannot import name 'CLoader' from 'ruamel.yaml' 
```

Which is a little strange, since `ruamel.yaml` doesn't say anything about not supporting Python 3.11 on pypi.org. And ditto, the `yamlize` library we use that is our sole importer of `ruamel.yaml` doesn't say anything about not supporting 3.11.

So, a little more research is needed.

**Comment by john-science** [comment]
[H5PY](https://pypi.org/project/h5py/3.8.0/#files) now has support for Windows on 3.11!

**Comment by opotowsky** [comment]
FYI `wxpython` doesn't yet have support for 3.11: https://pypi.org/project/wxPython/#files

**Comment by john-science** [comment]
Now new version of `wxpython` since Aug 2022, I see.  

Well, I say we press forward testing without `wxpython` for now.

@opotowsky Do you care to comment on the yaml error above?

**Comment by opotowsky** [comment]
> @Scthe current road block for getting ARMI working in Python 3.11 appears to be the [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) library. Our unit tests throw:
> 
> ```python
> armi/cli/reportsEntryPoint.py:21: in <module>
>     from armi.reactor import blueprints
> armi/reactor/blueprints/__init__.py:77: in <module>
>     from ruamel.yaml import CLoader, RoundTripLoader
> E   ImportError: cannot import name 'CLoader' from 'ruamel.yaml' 
> ```
> 
> Which is a little strange, since `ruamel.yaml` doesn't say anything about not supporting Python 3.11 on pypi.org. And ditto, the `yamlize` library we use that is our sole importer of `ruamel.yaml` doesn't say anything about not supporting 3.11.
> 
> So, a little more research is needed.

This was resolved with `ruamel.yaml.clib` being installed, i.e., just an added dependency!

**Comment by opotowsky** [comment]
Update: As long as we stick w `numpy 1.23.5` (versions above this fail for an unrelated reason) and add `ruamel.yaml.clib` as a dep the python 3.11 switch looks ~ready (as in I ran unit tests)

I haven't tested some of the dev deps, like sphinx et al, and there's the known `wxpython` issue.

**Comment by john-science** [comment]
Wow, Arrielle, that's awesome.

If that's the case, I would love to open a PR with the updated requirements file(s) and then add Python 3.11 to our unit tests:

https://github.com/terrapower/armi/blob/f1fd8204aa4ad3f8a51e66d1bf6583c0af3ce5b0/.github/workflows/unittests.yaml#L11

That would be a great way to check that not only does ARMI now support 3.11, but the new requirements didn't lose us support for 3.7 or something.

(We will also need to do some internal testing, outside of ARMI, to make sure this change doesn't break downstream repos.)

You rock! Thanks a billion!

**Comment by opotowsky** [comment]
Well....can we drop 3.7 support since python is? 

And yes I kind of blindly updated a bunch of deps, so we will need to test that we can get version combos of all the dependencies and still have things work. Still more work to do but it's a solid step we made yesterday!

**Comment by opotowsky** [comment]
`wxpython` now has a python 3.11 build! https://pypi.org/project/wxPython/#files

**Comment by john-science** [comment]
> Well....can we drop 3.7 support since python is?

@sombrereau Hey man, @opotowsky is asking if we can officially drop support for Python 3.7.   Do I remember this correctly, that your internal TP project is still focused on Python 3.7?

**Comment by opotowsky** [comment]
@sombrereau should just skip 3.9 and go 3.7 --> 3.11 😆
